### PR TITLE
Move ReForm to published

### PR DESCRIPTION
**Pull request by grsabreu**
### Why
It has now a more stable API, a live demo and README with informations

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! I'm in the middle of rewriting the source configuration to include more information, so I'll have to hold off on this for a day or two. You can help me out by giving me the extra information right away though. Just in a comment. This is the new source format (though subject to change):
```
    "bs-reform": {
      "type": "binding" | "library" | "tool" | "boilerplate",
      "condition": "maintained" | "neglected" | "deprecated",
      "platforms": ["browser" | "node" | "native" | "any"],
      "keywords": ["form"] // Overrides keywords in package.json, in case you want it to be different. Otherwise just leave out
    }
```
The published section needs the npm name (which seems to be bs-reform) rather than the github name you've given. You're also missing an installation section in the readme.

**Comment by grsabreu** [comment]
oh, nice! 
gonna add those changes

**Comment by grsabreu** [comment]
```
    "bs-reform": {
      "type": "library",
      "condition": "maintained",
      "platforms": ["browser" | "native"],
      "keywords": ["form"] // Overrides keywords in package.json, in case you want it to be different. Otherwise just leave out
    }
```

**Comment by grsabreu** [comment]
I think this got stale now since the data was moved to another repo, gonna close it

**Comment by glennsl** [comment]
Yep, I've added bs-reform and bs-reason-apollo there, but marked them as neglected due to missing installation instructions and incorrect description repectively. Let me know when that's fixed and I'll remove the flag.

I've also unlisted bs-restyled for having both those problems, as well as missing an example (and not being in a usable state I think?), and bs-react-native-router-flux for not having much of anything.

**Comment by grsabreu** [comment]
bs-restyled and bs-react-native-router-flux are not stable yet indeed
now ReForm I updated the instructions here https://www.npmjs.com/package/bs-reform#installation
and we're also moving the docs to docusaurus here https://astrocoders.com/reform/docs/installation.html

**Comment by glennsl** [comment]
Great, I've removed the flag then. Thanks!

**Pull request closed without merging**
