### PR TITLE
add 2 new packages

### PR DESCRIPTION
**Pull request by jaredly**

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! I think I'll have to add these manually since I screwed up by not pushing after reoganizing the sources locally.

Some remarks:
- Neither package specify the repository in package.json. They also don't specify homepage and bugs, but these'll be inferred from the repository URL if left out.
- Neither package specify "description" in package.json. This is the summary that will be displayed in lists and search results and such. If left out, it'll be inferred from the readme, but it's much better to be explicit about it. For reason-cli-tools the summary is currently "## `Files` module" .
- The keywords are a bit thin. Perhaps add "cli", "posix" and "cross-platform" to reason-cli-tools, and "http" and "native" to reason-simple-server.
- The readmes could use some more explanation and guidance. What's already there is good, but a sentence describing what it is and the state it's in, and an "Installation" section explaining how to get to the point of being able to write code would be great.
- While having the license in package.json is probably sufficient, having a LICENSE file in the repo with the terms of the license is good practice. It'll also enable GitHub to detect it.
- You might want to consider publishing the packages under the `@jaredly` npm scope. It seems to be emerging as a good practice now

I'll hold off on adding them until these have been addressed.

**Comment by glennsl** [comment]
Also, native-only packages are a bit of a bad fit right now. I need to add some categories to broadly classify these things. It'd make tooling feel more at home too.

**Comment by glennsl** [comment]
Closing this due to staleness. Please resubmit when the issues have been addressed.

**Comment by jaredly** [comment]
:) sounds good

**Pull request closed without merging**
