### PR TITLE
Fix typo on publish page (follwoing -> following)

### PR DESCRIPTION
**Pull request by wyze**

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! Good to see someone's reading it :)

**Comment by aantron** [comment]
AFAICT this typo is still live. I just came here to fix it, too.

**Comment by glennsl** [comment]
Ah, it seemed the typo had managed to reproduce before it got caught, by some mysterious process that just happens to look like a cut-and-paste job :flushed:

**Comment by aantron** [comment]
If you're about to fix it, there is a second instance of it in the adjacent section. I didn't open a PR for that because I wanted to know what's happening first :)

**Pull request merged**
